        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/createjs-2015.11.26.min.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/howler.min.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/screenfull.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/platform.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/ios_fullscreen.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/ctl_utils.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/sprite_lib.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/settings.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CSlotSettings.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CLang.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CPreloader.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CMain.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CTextButton.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CGfxButton.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CToggle.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CBetBut.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CMenu.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CGame.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CReelColumn.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CInterface.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CPayTablePanel.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CStaticSymbolCell.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CTweenController.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CCreditsPanel.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CCTLText.js"></script>
        <script type="text/javascript" src="<?php echo base_url() . 'assets/games/slot/'; ?>/js/CRechargePanel.js"></script>